vich_uploader:
    db_driver: orm

    mappings:
      covers:
        uri_prefix: /images/covers
        upload_destination: '%kernel.project_dir%/public/images/covers'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true